version: "3.8"

services:
  # --- User DB ---
  user_db:
    image: postgres
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # --- Product DB ---
  product_db:
    image: postgres
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    volumes:
      - product_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  # --- Migrate for User Service ---
  migrate:
    image: migrate/migrate
    depends_on:
      - user_db
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      sleep 10 &&
      migrate -path=/migrations -database=postgres://postgres:postgres@user_db:5432/user_db?sslmode=disable up
      "
    volumes:
      - ./user_service/migrations:/migrations
    restart: on-failure

  # --- Migrate for Product Service ---
  migrate_product:
    image: migrate/migrate
    depends_on:
      - product_db
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      sleep 10 &&
      migrate -path=/migrations -database=postgres://postgres:postgres@product_db:5432/product_db?sslmode=disable up
      "
    volumes:
      - ./product_service/migrations:/migrations
    restart: on-failure

  # --- User Service ---
  user_service:
    build:
      context: ./user_service
    depends_on:
      - user_db
    ports:
      - "8081:8080"
    environment:
      DB_URL: postgres://postgres:postgres@user_db:5432/user_db?sslmode=disable
      SECRET_KEY: supersecret

  # --- Product Service ---
  product_service:
    build:
      context: ./product_service
    depends_on:
      - product_db
    ports:
      - "8082:8080"
    environment:
      DB_URL: postgres://postgres:postgres@product_db:5432/product_db?sslmode=disable

  # --- Cart DB ---
  cart_db:
    image: postgres
    container_name: cart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cart_db
    volumes:
      - cart_pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  # --- Migrate for Cart Service ---
  migrate_cart:
    image: migrate/migrate
    depends_on:
      - cart_db
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      sleep 10 &&
      migrate -path=/migrations -database=postgres://postgres:postgres@cart_db:5432/cart_db?sslmode=disable up
      "
    volumes:
      - ./cart_service/migrations:/migrations
    restart: on-failure

  # --- Cart Service ---
  cart_service:
    build:
      context: ./cart_service
    depends_on:
      - cart_db
    ports:
      - "8083:8080"
    environment:
      DB_URL: postgres://postgres:postgres@cart_db:5432/cart_db?sslmode=disable

  # --- Order DB ---
  order_db:
    image: postgres
    container_name: order-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    volumes:
      - order_pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  # --- Migrate for Order Service ---
  migrate_order:
    image: migrate/migrate
    depends_on:
      - order_db
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      sleep 10 &&
      migrate -path=/migrations -database=postgres://postgres:postgres@order_db:5432/order_db?sslmode=disable up
      "
    volumes:
      - ./order_service/migrations:/migrations
    restart: on-failure

  # --- Order Service ---
  order_service:
    build:
      context: ./order_service
    depends_on:
      - order_db
    ports:
      - "8084:8080"
    environment:
      DB_URL: postgres://postgres:postgres@order_db:5432/order_db?sslmode=disable

  # --- Delivery DB ---
  delivery_db:
    image: postgres
    container_name: delivery-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery_db
    volumes:
      - delivery_pgdata:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  # --- Migrate for Delivery Service ---
  migrate_delivery:
    image: migrate/migrate
    depends_on:
      - delivery_db
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      sleep 10 &&
      migrate -path=/migrations -database=postgres://postgres:postgres@delivery_db:5432/delivery_db?sslmode=disable up
      "
    volumes:
      - ./delivery_service/migrations:/migrations
    restart: on-failure

  # --- Delivery Service ---
  delivery_service:
    build:
      context: ./delivery_service
    depends_on:
      - delivery_db
    ports:
      - "8085:8080"
    environment:
      DB_URL: postgres://postgres:postgres@delivery_db:5432/delivery_db?sslmode=disable
  ### 🔽 База данных для admin_service
  admin_db:
    image: postgres
    container_name: admin-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: admin_db
    ports:
      - "5436:5432"
    volumes:
      - admin_pgdata:/var/lib/postgresql/data

  ### 🔽 Миграции для admin_service
  migrate_admin:
    image: migrate/migrate
    depends_on:
      - admin_db
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "
      sleep 10 &&
      migrate -path=/migrations -database=postgres://postgres:postgres@admin_db:5432/admin_db?sslmode=disable up
      "
    volumes:
      - ./admin_service/migrations:/migrations
    restart: on-failure

  ### 🔽 Сам сервис admin
  admin_service:
    build:
      context: ./admin_service
    depends_on:
      - admin_db
    ports:
      - "8086:8080"
    environment:
      DB_URL: postgres://postgres:postgres@admin_db:5432/admin_db?sslmode=disable
      USER_SERVICE_URL: http://user_service:8080
volumes:
  user_pgdata:
  product_pgdata:
  cart_pgdata:
  order_pgdata:
  delivery_pgdata:
  admin_pgdata:



