services:
  db:
    image: postgres
    container_name: bd-gaultier
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./user_service/migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://postgres:postgres@db:5432/user_db?sslmode=disable",
        "up"
      ]
    restart: on-failure

  user_service:
    build:
      context: ./user_service
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/user_db?sslmode=disable
      SECRET_KEY: supersecret
volumes:
  user_pgdata:
